name: Build And Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  node-build:
    name: Build for production
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      # Checkout the repository
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Cache dependencies
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install and build the project
      - name: Install and Build
        run: |
          yarn install
          yarn build

      # Deploy to server using SSH
      - name: Deploy to Server
        uses: fifsky/ssh-action@v0.6.1
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd mrCityNode/
            git pull origin main
            npx prisma generate
            yarn build
            pm2 restart my-app