name: Build And Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  node-build:
    name: Build for production
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Checkout yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Compose build file on server
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          pass: ${{ secrets.SSH_PASSWORD }}
          command: |
            cd songkhla-xr-backend/
            git pull origin main
            npx prisma generate
            yarn build
            pm2 restart server
